name: complex_layout
description: A benchmark of a relatively complex layout.

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  # Also examples/flutter_gallery/pubspec.yaml
  flutter_gallery_assets:
    git:
      url: https://flutter.googlesource.com/gallery-assets
      ref: ef928550119411358b8b25e16aecde6ace513526

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - packages/flutter_gallery_assets/ali_connors.png
    - packages/flutter_gallery_assets/ali_connors_sml.png
    - packages/flutter_gallery_assets/top_10_australian_beaches.png
